<?php
if (!Mage::helper('customer')->isLoggedIn()) : ?>
   <!--loading-->
    <div class="bc-ajaxlogin-loader">
    </div>

   <!--login-->
    <div class="bc-login-window">
        <div class="bc-window-outside">
            <span class="close">x</span>

            <div class="bc-window-inside">
                <div class="bc-window-title">
                    <h3>
                        <?php echo $this->__('Login') ?>
                    </h3>
                </div>

                <div class="bc-window-box first">
                    <div class="bc-window-content">
                        <div class="input-fly bc-showhideme">
                            <label for="bc-email"><?php echo $this->__('E-mail address') ?> <span>*</span></label>
                            <input type="text" placeholder="<?php echo $this->__('E-mail address') ?>" id="bc-email" name="bc-email" value="" />
                            <div class="bc-ajaxlogin-error err-email err-noemail err-wrongemail err-wronglogin"></div>
                        </div>
                        <div class="input-fly bc-showhideme">
                            <label for="bc-password"><?php echo $this->__('Password') ?> <span>*</span></label>
                            <input type="password" placeholder="<?php echo $this->__('Password') ?>" id="bc-password" name="bc-password" value="" />
                            <div class="bc-ajaxlogin-error err-password err-dirtypassword err-nopassword err-longpassword"></div>
                        </div>
                    </div>
                </div>

                <div class="bc-window-box last">
                    <div class="bc-window-content box-contents box-contents-button bc-showhideme">
                        <span class="bc-forgot-password">
                            <a href="<?php echo Mage::getBaseUrl() ?>customer/account/forgotpassword/"><?php echo $this->__('Forgot Password') ?></a>
                        </span>
                        <button type="button" class="button btn-proceed-checkout btn-checkout bc-ajaxlogin-button">
                            <span>
                                <span>
                                    <?php echo $this->__('Login') ?>
                                </span>
                            </span>
                        </button>
                        <p id="y-to-register" class="bc-switch-window">
                            <?php echo $this->__('or registration') ?>
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>


    <!--register-->
    <div class="bc-register-window">
        <div class="bc-window-outside">
            <span class="close">×</span>

            <div class="bc-window-inside">
                <div class="bc-window-title">
                    <h3>
                        <?php echo $this->__('Registration') ?>
                    </h3>
                </div>

                <div class="bc-window-box first">
                    <div class="bc-window-subtitle bc-showhideme">
                        <p><?php echo $this->__('Profile Informations') ?></p>
                    </div>
                    <div class="bc-window-content">
                        <div class="input-fly bc-showhideme">
                            <label for="bc-firstname"><?php echo $this->__('First Name') ?> <span>*</span></label>
                            <input type="text" placeholder="<?php echo $this->__('First Name') ?>" id="bc-firstname" name="bc-firstname" value="" />
                            <div class="bc-ajaxlogin-error err-firstname err-nofirstname err-dirtyfirstname"></div>
                        </div>
                        <div class="input-fly bc-showhideme">
                            <label for="bc-lastname"><?php echo $this->__('Last Name') ?> <span>*</span></label>
                            <input type="text" placeholder="<?php echo $this->__('Last Name') ?>" id="bc-lastname" name="bc-lastname" value="" />
                            <div class="bc-ajaxlogin-error err-lastname err-nolastname err-dirtylastname"></div>
                        </div>
                        <div class="input-fly input-fly-checkbox bc-showhideme">
                            <input type="checkbox" id="bc-newsletter" name="bc-newsletter" value="ok" />
                            <label for="bc-newsletter"><?php echo $this->__('Subscribe to Newsletter') ?></label>
                        </div>
                    </div>
                </div>

                <div class="bc-window-box second">
                    <div class="bc-window-subtitle bc-showhideme">
                        <p><?php echo $this->__('Login Datas') ?></p>
                    </div>
                    <div class="bc-window-content">
                        <div class="input-fly bc-showhideme">
                            <label for="bc-email"><?php echo $this->__('E-mail address') ?> <span>*</span></label>
                            <input type="text" placeholder="<?php echo $this->__('E-mail address') ?>" id="bc-email" name="bc-email" value="" />
                            <div class="bc-ajaxlogin-error err-email err-noemail err-wrongemail err-emailisexist"></div>
                        </div>
                        <div class="input-fly bc-showhideme">
                            <label for="bc-password"><?php echo $this->__('Password') ?> <span>*</span></label>
                            <input type="password" placeholder="<?php echo $this->__('Password') ?>" id="bc-password" name="bc-password" value="" />
                            <div class="bc-ajaxlogin-error err-password err-dirtypassword err-nopassword err-shortpassword err-longpassword"></div>
                        </div>
                        <div class="input-fly bc-showhideme">
                            <label for="bc-passwordsecond"><?php echo $this->__('Password confirmation') ?> <span>*</span></label>
                            <input type="password" placeholder="<?php echo $this->__('Password confirmation') ?>" id="bc-passwordsecond" name="bc-passwordsecond" value="" />
                            <div class="bc-ajaxlogin-error err-passwordsecond err-nopasswordsecond err-notsamepasswords"></div>
                        </div>
                        <div class="input-fly input-fly-checkbox bc-showhideme">
                            <input type="checkbox" id="bc-licence" name="bc-licence" value="ok" />
                            <label for="bc-licence"><?php echo $this->__('I accept the') ?> <a href="#" target="_blank"><?php echo $this->__('Terms and Coditions') ?></a></label>
                            <div class="bc-ajaxlogin-error err-nolicence"></div>
                        </div>
                    </div>
                </div>

                <div class="bc-window-box last">
                    <div class="bc-window-content box-contents bc-showhideme">
                        <button type="button" class="button btn-proceed-checkout btn-checkout bc-ajaxlogin-button">
                            <span>
                                <span>
                                    <?php echo $this->__('Register') ?>
                                </span>
                            </span>
                        </button>
                        <p id="y-to-login" class="bc-switch-window">
                            <?php echo $this->__('or login') ?>
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!--error messages-->
    <div class="bc_ajaxlogin-temp-error" style="display:none !important;">
        <div class="ytmpa-nofirstname"><?php echo $this->__('First name is required!') ?></div>
        <div class="ytmpa-nolastname"><?php echo $this->__('Last name is required!') ?></div>
        <div class="ytmpa-dirtyfirstname"><?php echo $this->__('First name is not valid!') ?></div>
        <div class="ytmpa-dirtylastname"><?php echo $this->__('Last name is not valid!') ?></div>

        <div class="ytmpa-wrongemail"><?php echo $this->__('This is not an email address!') ?></div>
        <div class="ytmpa-noemail"><?php echo $this->__('Email address is required!') ?></div>
        <div class="ytmpa-emailisexist"><?php echo $this->__('This email is already registered!') ?></div>

        <div class="ytmpa-nopassword"><?php echo $this->__('Password is required!') ?></div>
        <div class="ytmpa-dirtypassword"><?php echo $this->__('Enter a valid password!') ?></div>
        <div class="ytmpa-shortpassword"><?php echo $this->__('Please enter 6 or more characters!') ?></div>
        <div class="ytmpa-longpassword"><?php echo $this->__('Please enter 16 or less characters!') ?></div>
        <div class="ytmpa-notsamepasswords"><?php echo $this->__('Passwords are not same!') ?></div>
        <div class="ytmpa-nolicence"><?php echo $this->__('Terms and Conditions are required!') ?></div>

        <div class="ytmpa-wronglogin"><?php echo $this->__('Email or Password is wrong!') ?></div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        jQuery(document).ready(function(){
            jQuery().bcAjaxLogin({
                redirection : '<?php echo $this->isRedirectToProfile() ?>',
                profileUrl : '<?php echo Mage::getBaseUrl() ?>customer/account/',
                autoShowUp : '<?php echo $autoShowUp = (isset($_GET['ajaxlogin'])) ? 'yes' : 'no' ?>',
                controllerUrl : '<?php echo $this->getUrl('bc_login//index') ?>'
            });
        });
        //]]>
    </script>
<?php endif;?>
